### PR TITLE
Fixed render bug, improved code quality, removed most compiler warnings, improved custom exception handling

### LINKED ISSUE #28: Closing File selector leads to error, showing error bar
Opening a Sequence from a folder, then closing the OS-File-selection-window via escape throws an error which triggers the error bar

### PR DESCRIPTION
**Pull request by nTerior**
Closes #28

### CODE REVIEW

File: BEAM/Models/Configuration.cs [hunk 1]
```diff
@@ -31,7 +31,7 @@ public static Configuration AttemptLoad(string path)
             var config = JsonSerializer.Deserialize<Configuration>(json);
             return config ?? StandardEnglish();
         }
-        catch (Exception e)
+        catch (Exception)
         {
```
Comment (HAL899) [inline BEAM/Models/Configuration.cs:35]: Catching standard exception not good style

File: BEAM/Profiling/Timer.cs [hunk 2]
```diff
@@ -13,7 +13,7 @@ public class TimerEventArgs(string name, Stopwatch watch)
 
 public class TimerScopeToken(string name, Stopwatch watch) : IDisposable
 {
-    public event TimerEndEvent OnTimerEnd;
+    public event TimerEndEvent OnTimerEnd = delegate { };
```
Comment (HAL899) [inline BEAM/Profiling/Timer.cs:17]: Assuming these to be default instantiations with no effect on the program

File: BEAM/Models/Log/Logger.cs [hunk 3]
```diff
@@ -15,7 +13,7 @@ public partial class Logger : ObservableObject, ILog
     private LogLevel _logLevel;
     private LogEvent _logEvent;
 
-    private ObservableCollection<LogEntry> _LogEntries;
+    private ObservableCollection<Models.Log.LogEntry> _LogEntries;
```
Comment (HAL899) [inline BEAM/Models/Log/Logger.cs:17]: If you are in namespace BEAM.Models.Log, why not use LogEntry directly?

File: BEAM/Views/SequenceView.axaml.cs [hunk 4]
```diff
@@ -149,21 +143,22 @@ private void _SetPlottable(BitmapPlottable plottable)
...
         PreparePlot();
-        
+
         var isDark = Application.Current!.ActualThemeVariant == ThemeVariant.Dark;
         var checkerBoard = new CheckerboardPlottable(isDark);
         AvaPlot1.Plot.Add.Plottable(checkerBoard);
-        
+
+        // sets the plottable
         _SetPlottable(new BitmapPlottable(vm.Sequence, vm.CurrentRenderer));
```
Comment (HAL899) [inline BEAM/Views/SequenceView.axaml.cs:155]: Comment unecessary due to understandable name of following function

**Review by HAL899 — APPROVED** [review]
Most updates were simple.
No greater changes were introduced, that I saw.
I however do not understand the effectiveness of some alterations.
